version: "3.3"
services:
  bot:
    build:
      context: .
    volumes:
      - ./:/root/rs-club-bot
    environment:
      - PYTHONPATH=/root/rs-club-bot
    env_file:
      - environment.env
    working_dir: /root/rs-club-bot
    command: ["python", "/root/rs-club-bot/bot.py"]